import type { SlashCommandItem } from "@/lib/editor/slashCommandTypes";

export const coreSlashCommands: SlashCommandItem[] = [
  // ── 기본 블록 ────────────────────────────────────────────────
  {
    id: "text",
    title: "텍스트",
    description: "일반 텍스트 단락",
    icon: "Type",
    category: "basic",
    keywords: ["text", "paragraph", "텍스트", "단락"],
  },
  {
    id: "h1",
    title: "제목 1",
    description: "최상위 수준 제목",
    icon: "Heading1",
    category: "basic",
    shortcut: "#",
    keywords: ["heading", "h1", "제목"],
  },
  {
    id: "h2",
    title: "제목 2",
    description: "두 번째 수준 제목",
    icon: "Heading2",
    category: "basic",
    shortcut: "##",
    keywords: ["heading", "h2", "제목"],
  },
  {
    id: "h3",
    title: "제목 3",
    description: "세 번째 수준 제목",
    icon: "Heading3",
    category: "basic",
    shortcut: "###",
    keywords: ["heading", "h3", "제목"],
  },
  {
    id: "h4",
    title: "제목 4",
    description: "네 번째 수준 제목",
    icon: "Heading4",
    category: "basic",
    shortcut: "####",
    keywords: ["heading", "h4", "제목"],
  },
  {
    id: "h5",
    title: "제목 5",
    description: "다섯 번째 수준 제목",
    icon: "Heading5",
    category: "basic",
    keywords: ["heading", "h5", "제목"],
  },
  {
    id: "h6",
    title: "제목 6",
    description: "여섯 번째 수준 제목",
    icon: "Heading6",
    category: "basic",
    keywords: ["heading", "h6", "제목"],
  },
  {
    id: "bulletList",
    title: "글머리 목록",
    description: "순서 없는 불릿 목록",
    icon: "List",
    category: "basic",
    shortcut: "-",
    keywords: ["bullet", "list", "글머리", "목록"],
  },
  {
    id: "orderedList",
    title: "번호 목록",
    description: "번호 매기기 목록",
    icon: "ListOrdered",
    category: "basic",
    shortcut: "1.",
    keywords: ["ordered", "numbered", "번호", "목록"],
  },
  {
    id: "taskList",
    title: "할일 목록",
    description: "체크박스 할일 목록",
    icon: "CheckSquare",
    category: "basic",
    shortcut: "- [ ]",
    keywords: ["task", "todo", "check", "할일", "체크"],
  },
  {
    id: "toggleList",
    title: "토글 목록",
    description: "접을 수 있는 목록",
    icon: "ChevronRight",
    category: "basic",
    shortcut: "gt",
    isDisabled: true,
    keywords: ["toggle", "토글", "접기"],
  },
  {
    id: "blockquote",
    title: "인용",
    description: "인용문 블록",
    icon: "Quote",
    category: "basic",
    shortcut: ">",
    keywords: ["quote", "blockquote", "인용"],
  },
  {
    id: "divider",
    title: "구분선",
    description: "수평 구분선",
    icon: "Minus",
    category: "basic",
    shortcut: "---",
    keywords: ["divider", "hr", "rule", "구분선"],
  },
  {
    id: "callout",
    title: "콜아웃",
    description: "강조 메시지 박스",
    icon: "AlertCircle",
    category: "basic",
    isDisabled: true,
    keywords: ["callout", "alert", "콜아웃", "강조"],
  },
  {
    id: "tableBlock",
    title: "표",
    description: "행과 열로 구성된 표",
    icon: "Table",
    category: "basic",
    isDisabled: true,
    keywords: ["table", "표", "행", "열"],
  },
  {
    id: "toc",
    title: "목차",
    description: "페이지 목차 자동 생성",
    icon: "BookOpen",
    category: "basic",
    isDisabled: true,
    keywords: ["toc", "contents", "목차"],
  },

  // ── 미디어 ──────────────────────────────────────────────────
  {
    id: "image",
    title: "이미지",
    description: "이미지 업로드 또는 URL 삽입",
    icon: "Image",
    category: "media",
    keywords: ["image", "photo", "이미지", "사진"],
  },
  {
    id: "video",
    title: "동영상",
    description: "동영상 업로드 또는 URL 삽입",
    icon: "Video",
    category: "media",
    isDisabled: true,
    keywords: ["video", "movie", "동영상"],
  },
  {
    id: "audio",
    title: "오디오",
    description: "오디오 파일 업로드",
    icon: "Music",
    category: "media",
    isDisabled: true,
    keywords: ["audio", "sound", "오디오", "음악"],
  },
  {
    id: "file",
    title: "파일",
    description: "파일 첨부",
    icon: "Paperclip",
    category: "media",
    isDisabled: true,
    keywords: ["file", "attachment", "파일", "첨부"],
  },
  {
    id: "bookmark",
    title: "북마크",
    description: "링크를 북마크로 저장",
    icon: "Bookmark",
    category: "media",
    isDisabled: true,
    keywords: ["bookmark", "link", "북마크"],
  },

  // ── 코드 ────────────────────────────────────────────────────
  {
    id: "codeBlock",
    title: "코드 블록",
    description: "언어 선택 + 실행 분할뷰",
    icon: "Code2",
    category: "code",
    shortcut: "```",
    keywords: ["code", "코드", "snippet", "언어"],
  },
  {
    id: "mermaid",
    title: "Mermaid",
    description: "다이어그램 및 플로우차트",
    icon: "GitBranch",
    category: "code",
    isDisabled: true,
    keywords: ["mermaid", "diagram", "chart", "다이어그램", "플로우"],
  },

  // ── 데이터베이스 ─────────────────────────────────────────────
  {
    id: "dbTable",
    title: "표 보기",
    description: "데이터베이스 표 보기",
    icon: "Table2",
    category: "database",
    keywords: ["database", "table", "표", "데이터베이스"],
  },
  {
    id: "dbBoard",
    title: "보드 보기",
    description: "칸반 보드 보기",
    icon: "Kanban",
    category: "database",
    isDisabled: true,
    keywords: ["board", "kanban", "보드"],
  },
  {
    id: "dbGallery",
    title: "갤러리 보기",
    description: "카드 갤러리 보기",
    icon: "LayoutGrid",
    category: "database",
    isDisabled: true,
    keywords: ["gallery", "갤러리", "카드"],
  },
  {
    id: "dbList",
    title: "리스트 보기",
    description: "간단한 목록 보기",
    icon: "LayoutList",
    category: "database",
    isDisabled: true,
    keywords: ["list", "리스트"],
  },
  {
    id: "dbCalendar",
    title: "캘린더 보기",
    description: "달력 형식 보기",
    icon: "Calendar",
    category: "database",
    isDisabled: true,
    keywords: ["calendar", "캘린더", "달력"],
  },
  {
    id: "dbTimeline",
    title: "타임라인 보기",
    description: "간트 차트 형식",
    icon: "GanttChart",
    category: "database",
    isDisabled: true,
    keywords: ["timeline", "gantt", "타임라인", "간트"],
  },
];
